name: clean_architecture_bloc
description: Flutter template.

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  fresh_dio:
  get_it: ^7.2.0
  json_serializable: ^6.1.4
  json_annotation: ^4.4.0
  auto_route: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  auto_route_generator: ^6.2.0

flutter:

  uses-material-design: true
